[theme]
primaryColor = "#3498db"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#1f2933"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
